# NLP with Bert for Sentiment Analysis

In [1]:
!pip3 install ktrain

     |████████████████████████████████| 25.3MB 120kB/s 
     |████████████████████████████████| 6.8MB 41.2MB/s 
     |████████████████████████████████| 983kB 43.3MB/s 
     |████████████████████████████████| 266kB 52.0MB/s 
     |████████████████████████████████| 1.9MB 37.0MB/s 
     |████████████████████████████████| 1.2MB 38.3MB/s 
     |████████████████████████████████| 471kB 49.6MB/s 
     |████████████████████████████████| 3.3MB 53.1MB/s 
     |████████████████████████████████| 901kB 41.0MB/s 
  Created wheel for ktrain: filename=ktrain-0.26.3-cp37-none-any.whl size=25282380 sha256=12332b60d8be9f2744b32f988ed47c1a8ea6850099b72bc35bbd412665feba45
  Stored in directory: /root/.cache/pip/wheels/16/05/be/d6e659b3349016b1059e19fa028f165af4eeae2c196f329112
  Created wheel for langdetect: filename=langdetect-1.0.9-cp37-none-any.whl size=993223 sha256=6adb79043e52d44b090c2b609a0f959aa237c70fed83d005c9099502a2e0ea2f
  Stored in directory: /root/.cache/pip/wheels/7e/18/13/038c34057808931c7d

### Importing the libraries

In [2]:
import os.path
import numpy as np
import tensorflow as tf
import ktrain
from ktrain import text

## Part 1: Data Preprocessing

### Loading the IMDB dataset

In [3]:
dataset = tf.keras.utils.get_file(fname="aclImdb_v1.tar.gz",
                                  origin="http://ai.stanford.edu/~amaas/data/sentiment/aclImdb_v1.tar.gz",
                                  extract=True)
IMDB_DATADIR = os.path.join(os.path.dirname(dataset),'aclImdb')

84131840/84125825 [==============================] - 3s 0us/step


In [4]:
os.path.join(dataset)

'/root/.keras/datasets/aclImdb_v1.tar.gz'

In [5]:
IMDB_DATADIR

'/root/.keras/datasets/aclImdb'

### Creating the training and test sets

In [6]:
(X_train,y_train), (X_test, y_test), preproc = text.texts_from_folder(IMDB_DATADIR,
                                                                      classes = ['pos','neg'],
                                                                      maxlen = 500,
                                                                      train_test_names = ['train','test'],
                                                                      preprocess_mode = 'bert')

detected encoding: utf-8
downloading pretrained BERT model (uncased_L-12_H-768_A-12.zip)...
[██████████████████████████████████████████████████]
extracting pretrained BERT model...
done.

cleanup downloaded zip...
done.

preprocessing train...
language: en


Is Multi-Label? False
preprocessing test...
language: en


In [7]:
(X_train,y_train)

([array([[ 101, 5717, 2154, ...,    0,    0,    0],
         [ 101, 2616, 2064, ...,    0,    0,    0],
         [ 101, 3071, 3248, ...,    0,    0,    0],
         ...,
         [ 101, 3083, 3427, ...,    0,    0,    0],
         [ 101, 1045, 3422, ...,    0,    0,    0],
         [ 101, 7078, 1996, ...,    0,    0,    0]]),
  array([[0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         ...,
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0]])],
 array([[0., 1.],
        [1., 0.],
        [0., 1.],
        ...,
        [1., 0.],
        [1., 0.],
        [1., 0.]], dtype=float32))

In [8]:
(X_test, y_test)

([array([[  101,  2320,  2153, ...,     0,     0,     0],
         [  101,  2023,  2003, ...,     0,     0,     0],
         [  101,  2034,  1997, ...,     0,     0,     0],
         ...,
         [  101,  2013,  1996, ..., 18605,  1010,   102],
         [  101,  2023,  3185, ...,     0,     0,     0],
         [  101,  1045,  1005, ...,     0,     0,     0]]),
  array([[0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         ...,
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0]])],
 array([[1., 0.],
        [1., 0.],
        [1., 0.],
        ...,
        [0., 1.],
        [0., 1.],
        [0., 1.]], dtype=float32))

In [9]:
preproc

## Part 2: Building the BERT model

In [10]:
model = text.text_classifier('bert',
                             train_data = (X_train,y_train),
                             preproc = preproc)

Is Multi-Label? False
maxlen is 500
done.


## Part 3: Training the BERT model

In [11]:
learner_instance = ktrain.get_learner(model, train_data = (X_train,y_train),
                               val_data = (X_test, y_test), batch_size = 6)

In [12]:
learner_instance.fit_onecycle(lr = 2e-5, epochs  = 1)



begin training using onecycle policy with max lr of 2e-05...
4167/4167 [==============================] - 5281s 1s/step - loss: 0.3435 - accuracy: 0.8439 - val_loss: 0.1634 - val_accuracy: 0.9391
