# Artificial Neural Network

This is a part of neural networks where we implemet classic neural network models without using any other layer like conv2d etc. In this notebook we are working on a regression model where we have constructed a ANN model with 2 hidden layers with 6 units each and we have used refictier activation function(relu) in the two hidden layers and  there is no activation function in the output layer when working with regression. We have chosed the optimizer as adam to implement Stochastic Gradient Descent and the loss as mean-squared-error. Also we have implemented Batch Gradient Descent method for minimizing the loss by dividing the data into batch_size of 32.

### Importing the libraries

In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf

In [2]:
tf.__version__

'2.4.1'

## Part 1 - Data Preprocessing

### Importing the dataset

In [3]:
dataset = pd.read_excel('reg_data.xlsx')
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

In [4]:
X

array([[  14.96,   41.76, 1024.07,   73.17],
       [  25.18,   62.96, 1020.04,   59.08],
       [   5.11,   39.4 , 1012.16,   92.14],
       ...,
       [  31.32,   74.33, 1012.92,   36.48],
       [  24.48,   69.45, 1013.86,   62.39],
       [  21.6 ,   62.52, 1017.23,   67.87]])

In [5]:
y

array([463.26, 444.37, 488.56, ..., 429.57, 435.74, 453.28])

### Splitting the dataset into the Training set and Test set

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.2)

## Part 2 - Building the ANN

### Initializing the ANN

In [7]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [8]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

### Adding the second hidden layer

In [9]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

### Adding the output layer

In [10]:
ann.add(tf.keras.layers.Dense(units=1))

## Part 3 - Training the ANN

### Compiling the ANN

In [11]:
ann.compile(optimizer = 'adam', loss = 'mean_squared_error')

### Training the ANN model on the Training set

In [12]:
ann.fit(X_train,y_train, batch_size = 32, epochs = 100)

Epoch 1/100
240/240 [==============================] - 1s 1ms/step - loss: 147541.3889
Epoch 2/100
240/240 [==============================] - 0s 1ms/step - loss: 190.2027
Epoch 3/100
240/240 [==============================] - 0s 1ms/step - loss: 180.8925
Epoch 4/100
240/240 [==============================] - 0s 1ms/step - loss: 171.8721
Epoch 5/100
240/240 [==============================] - 0s 1ms/step - loss: 170.9400
Epoch 6/100
240/240 [==============================] - 0s 1ms/step - loss: 172.2041
Epoch 7/100
240/240 [==============================] - 0s 1ms/step - loss: 159.1048
Epoch 8/100
240/240 [==============================] - 0s 1ms/step - loss: 151.8606
Epoch 9/100
240/240 [==============================] - 0s 1ms/step - loss: 147.0083
Epoch 10/100
240/240 [==============================] - 0s 1ms/step - loss: 135.5917
Epoch 11/100
240/240 [==============================] - 0s 1ms/step - loss: 129.7243
Epoch 12/100
240/240 [==============================] - 0s 1ms/step - l

### Predicting the results of the Test set

In [16]:
y_pred = ann.predict(X_test)
y_pred, y_test

(array([[482.22226],
        [454.19165],
        [444.8443 ],
        ...,
        [437.81244],
        [471.6461 ],
        [432.36984]], dtype=float32),
 array([485.06, 448.46, 430.45, ..., 440.13, 468.8 , 435.82]))